name: Publish NuGet Package to GitHub Packages and NuGet.org

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          PACKAGE_VERSION=""
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}
          fi

          if [[ -z "$PACKAGE_VERSION" && $GITHUB_REF == refs/tags/* ]]; then
            PACKAGE_VERSION=${GITHUB_REF#refs/tags/}
          fi
          
          if [[ -z "$PACKAGE_VERSION" ]]; then
            dotnet pack --configuration Release --no-build --output ./nupkgs
          else
            dotnet pack --configuration Release --no-build --output ./nupkgs -p:PackageVersion=$PACKAGE_VERSION
          fi

      - name: Publish to GitHub Packages
        if: always()
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY_ENV: ${{ secrets.NUGET_API_KEY }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') && env.NUGET_API_KEY_ENV != '' }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate